package stocks.view.stock;

import java.awt.event.ActionListener;

import stocks.controller.GUIController;
import stocks.view.GUIView;

/**
 * The following class represents the Buy Stock by Amount panel.
 */
public class BuyStockByAmount extends javax.swing.JPanel implements GUIView {

  GUIController controller;
  private javax.swing.JComboBox<String> bSAPortfolioId;
  private javax.swing.JButton bSASave;
  private javax.swing.JTextField bSAAmountTxt;
  private javax.swing.JTextField bSACommissionRateTxt;
  private javax.swing.JTextField bSADateTxt;
  private javax.swing.JLabel bSAErrorLbl;
  private javax.swing.JTextField bSATickerSymbolTxt;


  /**
   * Creates new form BuyStockByAmount
   *
   * @param controller the GUIController object.
   */
  public BuyStockByAmount(GUIController controller) {
    initComponents();
    this.controller = controller;
    controller.setBuyStockByAmountView(this);
    bSASave.setActionCommand("bSASave");

    bSAPortfolioId.removeAllItems();
    bSAPortfolioId.addItem("Select");
    String portfolios = controller.getExistingPortfolios();
    if (!portfolios.isEmpty()) {
      String[] portfolioList = portfolios.substring(1).split("\n");
      for (String port : portfolioList) {
        bSAPortfolioId.addItem(port);
      }
    }

    this.bSAAmountTxt = bSAAmountTxt;
    this.bSACommissionRateTxt = bSACommissionRateTxt;
    this.bSADateTxt = bSADateTxt;
    this.bSAErrorLbl = bSAErrorLbl;
    this.bSATickerSymbolTxt = bSATickerSymbolTxt;


  }

  /**
   * The following method executes the action listener method.
   *
   * @param listener the ActionListener object.
   */
  @Override
  public void addActionListener(ActionListener listener) {
    bSASave.addActionListener(listener);
  }


  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {


    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;

    jLabel1 = new javax.swing.JLabel();
    bSAPortfolioId = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    bSATickerSymbolTxt = new javax.swing.JTextField();
    bSACommissionRateTxt = new javax.swing.JTextField();
    bSAAmountTxt = new javax.swing.JTextField();
    bSADateTxt = new javax.swing.JTextField();
    bSASave = new javax.swing.JButton();
    bSAErrorLbl = new javax.swing.JLabel();

    jLabel1.setText("SELECT PORTFOLIO");

    bSAPortfolioId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
            {"Item 1", "Item 2", "Item 3", "Item 4"}));

    jLabel2.setText("ENTER TICKER SYMBOL");

    jLabel3.setText("ENTER COMMISSION RATE");

    jLabel4.setText("ENTER AMOUNT");

    jLabel5.setText("ENTER DATE (MM/DD/YYYY)");

    bSASave.setText("Save");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(bSASave)
                                    .addComponent(jLabel3)
                                    .addComponent(bSAErrorLbl, javax.swing.GroupLayout
                                                    .PREFERRED_SIZE,
                                            276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                            .Alignment.TRAILING, false)
                                            .addComponent(bSAPortfolioId, javax.swing.GroupLayout
                                                            .Alignment.LEADING,
                                                    0,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                            .addComponent(bSATickerSymbolTxt,
                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bSACommissionRateTxt,
                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bSAAmountTxt,
                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bSADateTxt,
                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout
                                                            .Alignment.LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)))
                            .addContainerGap(114, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSAPortfolioId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSATickerSymbolTxt,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSACommissionRateTxt,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSAAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSADateTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bSASave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSAErrorLbl)
                            .addContainerGap(39, Short.MAX_VALUE))
    );
  }
  // End of variables declaration//GEN-END:variables
}
