package stocks.view.stock;

import java.awt.event.ActionListener;

import stocks.controller.GUIController;
import stocks.view.GUIView;

/**
 * The following class represents the buy stock by volume panel.
 */
public class BuyStockByVolume extends javax.swing.JPanel implements GUIView {

  GUIController controller;
  private javax.swing.JComboBox bSVPortfolioId;
  private javax.swing.JButton bSVSave;
  private javax.swing.JTextField bSVCommissionRateTxt;
  private javax.swing.JTextField bSVDateTxt;
  private javax.swing.JLabel bSVErrorLbl;
  private javax.swing.JTextField bSVTickerSymbolTxt;
  private javax.swing.JTextField bSVVolumeTxt;

  /**
   * Creates new form BuyStockByVolume
   *
   * @param controller the GUIController object.
   */
  public BuyStockByVolume(GUIController controller) {
    initComponents();
    this.controller = controller;
    controller.setBuyStockByVolumeView(this);
    bSVSave.setActionCommand("bSVSave");

    bSVPortfolioId.removeAllItems();
    bSVPortfolioId.addItem("Select");
    String portfolios = controller.getExistingPortfolios();
    if (!portfolios.isEmpty()) {
      String[] portfolioList = portfolios.substring(1).split("\n");
      for (String port : portfolioList) {
        bSVPortfolioId.addItem(port);
      }
    }

    this.bSVVolumeTxt = bSVVolumeTxt;
    this.bSVCommissionRateTxt = bSVCommissionRateTxt;
    this.bSVDateTxt = bSVDateTxt;
    this.bSVErrorLbl = bSVErrorLbl;
    this.bSVTickerSymbolTxt = bSVTickerSymbolTxt;
  }

  /**
   * The following method executes the button operation.
   *
   * @param listener the ActionListener object.
   */

  @Override
  public void addActionListener(ActionListener listener) {
    bSVSave.addActionListener(listener);
  }


  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {


    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JTextField jTextField4;

    jTextField4 = new javax.swing.JTextField();
    bSVPortfolioId = new javax.swing.JComboBox();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    bSVTickerSymbolTxt = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    bSVDateTxt = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    bSVVolumeTxt = new javax.swing.JTextField();
    bSVSave = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    bSVCommissionRateTxt = new javax.swing.JTextField();
    bSVErrorLbl = new javax.swing.JLabel();

    jTextField4.setText("jTextField4");

    bSVPortfolioId.setModel(new javax.swing.DefaultComboBoxModel(new String[]
            {"Item 1", "Item 2", "Item 3", "Item 4"}));
    bSVPortfolioId.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BSVPortfolioIdActionPerformed(evt);
      }
    });

    jLabel1.setText("ENTER TICKER SYMBOL");

    jLabel2.setText("SELECT PORTFOLIO");

    jLabel3.setText("ENTER DATE (MM/DD/YYYY) ");

    jLabel4.setText("ENTER THE VOLUME");

    bSVSave.setText("Save");

    jLabel5.setText("ENTER COMMISSION RATE");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing
                                                    .GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(bSVCommissionRateTxt,
                                                            javax.swing.GroupLayout
                                                                    .Alignment.LEADING)
                                                    .addComponent(bSVPortfolioId,
                                                            javax.swing.GroupLayout
                                                                    .Alignment.LEADING,
                                                            0, 167, Short.MAX_VALUE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout
                                                            .Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout
                                                            .Alignment.LEADING)
                                                    .addComponent(bSVTickerSymbolTxt,
                                                            javax.swing.GroupLayout.Alignment
                                                                    .LEADING,
                                                            javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE,
                                                            167, Short.MAX_VALUE)
                                                    .addComponent(bSVSave,
                                                            javax.swing.GroupLayout
                                                                    .Alignment.LEADING)
                                                    .addComponent(bSVDateTxt, javax.swing
                                                                    .GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            166, javax.swing.GroupLayout
                                                                    .PREFERRED_SIZE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout
                                                            .Alignment.LEADING))
                                            .addGap(79, 214, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup().addGroup
                                            (layout.createParallelGroup(javax.swing.GroupLayout
                                                    .Alignment.LEADING)
                                                    .addComponent(bSVVolumeTxt,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            166,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(bSVErrorLbl))
                                            .addGap(0, 0, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addGap(9, 9, 9)
                            .addComponent(bSVPortfolioId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSVTickerSymbolTxt
                                    , javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSVCommissionRateTxt,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSVVolumeTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSVDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bSVSave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSVErrorLbl)
                            .addContainerGap(46, Short.MAX_VALUE))
    );
  }

  /**
   * The following method represents the Portfolio action performed.
   *
   * @param evt the ActionEvent object.
   */
  private void BSVPortfolioIdActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }
}
