/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stocks.view.stock;

import java.awt.event.ActionListener;
import java.lang.reflect.Field;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JTextField;

import stocks.controller.GUIController;
import stocks.view.GUIView;

/**
 *
 * @author Animesh Mane
 */
public class BuyStockByAmount extends javax.swing.JPanel implements GUIView{
    
    GUIController controller;

    /**
     * Creates new form BuyStockByAmount
     */
    public BuyStockByAmount(GUIController controller) {
        initComponents();
        this.controller = controller;
        controller.setBuyStockByAmountView(this);
        BSASave.setActionCommand("BSASave");
        
        BSAPortfolioId.removeAllItems();
        BSAPortfolioId.addItem("Select");
        String portfolios = controller.getExistingPortfolios();
        if(!portfolios.isEmpty()){
            String[] portfolioList = portfolios.substring(1).split("\n");
            for(String port:portfolioList){
                BSAPortfolioId.addItem(port);
            }
        }

        
    }

    @Override
    public void addActionListener(ActionListener listener) {
      BSASave.addActionListener(listener);
    }

    @Override
    public void setSummaryData(Map<String, Map<String, Double>> data) {

    }

    @Override
    public String getTextFieldData(String fieldName) {
        try{
            Object o = this; // The object you want to inspect
            Class<?> c = o.getClass();
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            JTextField portfolioName = (JTextField) f.get(o);
            return portfolioName.getText();
        }catch(NoSuchFieldException | IllegalAccessException i){
            throw new IllegalArgumentException("No such field found.\n");
        }
    }

    @Override
    public String getComboFieldData(String fieldName) {
        try{
            Object o = this; // The object you want to inspect
            Class<?> c = o.getClass();
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            JComboBox<String> portfolioName = (JComboBox<String>) f.get(o);
            return (String)portfolioName.getSelectedItem();
        }catch(NoSuchFieldException | IllegalAccessException i){
            throw new IllegalArgumentException("No such field found.\n");
        }
    }

    @Override
    public void clearTextFieldData(String fieldName) {
        try{
            Object o = this; // The object you want to inspect
            Class<?> c = o.getClass();
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            JTextField portfolioName = (JTextField) f.get(o);
            portfolioName.setText("");
        }catch(NoSuchFieldException | IllegalAccessException i){
            throw new IllegalArgumentException("No such field found.\n");
        }
    }

    @Override
    public void setErrorMessage(String fieldName, String message) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BSAPortfolioId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BSATickerSymbolTxt = new javax.swing.JTextField();
        BSACommissionRateTxt = new javax.swing.JTextField();
        BSAAmountTxt = new javax.swing.JTextField();
        BSADateTxt = new javax.swing.JTextField();
        BSASave = new javax.swing.JButton();
        BSAErrorLbl = new javax.swing.JLabel();

        jLabel1.setText("SELECT PORTFOLIO");

        BSAPortfolioId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("ENTER TICKER SYMBOL");

        jLabel3.setText("ENTER COMMISSION RATE");

        jLabel4.setText("ENTER AMOUNT");

        jLabel5.setText("ENTER DATE (MM/DD/YYYY)");

        BSASave.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(BSASave)
                    .addComponent(jLabel3)
                    .addComponent(BSAErrorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BSAPortfolioId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSATickerSymbolTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BSACommissionRateTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BSAAmountTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BSADateTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSAPortfolioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSATickerSymbolTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSACommissionRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSAAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSADateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BSASave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSAErrorLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BSAAmountTxt;
    private javax.swing.JTextField BSACommissionRateTxt;
    private javax.swing.JTextField BSADateTxt;
    private javax.swing.JLabel BSAErrorLbl;
    private javax.swing.JComboBox<String> BSAPortfolioId;
    private javax.swing.JButton BSASave;
    private javax.swing.JTextField BSATickerSymbolTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
