
package stocks.view.stock;

import stocks.controller.GUIController;
/**
 * The following class represents the main stock panel.
 */
public class StockMain extends javax.swing.JPanel {

  GUIController controller;

  /**
   * Creates new form StockMain
   * @param controller the GUIController object.
   */
  public StockMain(GUIController controller) {
    initComponents();
    this.controller = controller;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel3 = new javax.swing.JPanel();
    buyStockByAmountBtn = new javax.swing.JButton();
    buyStockByVolumeBtn = new javax.swing.JButton();
    viewStocksBtn = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();

    buyStockByAmountBtn.setText("Buy Stock By Amount");
    buyStockByAmountBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buyStockByAmountBtnActionPerformed(evt);
      }
    });

    buyStockByVolumeBtn.setText("Buy Stock By Volume");
    buyStockByVolumeBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buyStockByVolumeBtnActionPerformed(evt);
      }
    });

    viewStocksBtn.setText("View Stocks");
    viewStocksBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewStocksBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.LEADING)
                                    .addComponent(buyStockByAmountBtn)
                                    .addGroup(jPanel3Layout.createParallelGroup
                                            (javax.swing.GroupLayout.Alignment.TRAILING,
                                                    false)
                                            .addComponent(viewStocksBtn,
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                            .addComponent(buyStockByVolumeBtn,
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(buyStockByAmountBtn)
                            .addGap(18, 18, 18)
                            .addComponent(buyStockByVolumeBtn)
                            .addGap(18, 18, 18)
                            .addComponent(viewStocksBtn)
                            .addContainerGap(172, Short.MAX_VALUE))
    );

    jSplitPane1.setLeftComponent(jPanel3);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 359, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 305, Short.MAX_VALUE)
    );

    jSplitPane1.setRightComponent(jPanel4);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
    );
  }

  /**
   * The following method executes the buy stock action performed.
   * @param evt the ActionEvent object.
   */
  private void buyStockByVolumeBtnActionPerformed(java.awt.event.ActionEvent evt) {
    BuyStockByVolume pf = new BuyStockByVolume(controller);
    jSplitPane1.setRightComponent(pf);
  }

  /**
   * The following method executes the buy stock action performed.
   * @param evt the ActionEvent object.
   */
  private void viewStocksBtnActionPerformed(java.awt.event.ActionEvent evt) {
    ViewPortfolioStocks pf = new ViewPortfolioStocks(controller);
    jSplitPane1.setRightComponent(pf);
  }

  /**
   * The following method executes the buy stock action performed.
   * @param evt the ActionEvent object.
   */
  private void buyStockByAmountBtnActionPerformed(java.awt.event.ActionEvent evt) {
    BuyStockByAmount pf = new BuyStockByAmount(controller);
    jSplitPane1.setRightComponent(pf);
  }

  private javax.swing.JButton buyStockByAmountBtn;
  private javax.swing.JButton buyStockByVolumeBtn;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JButton viewStocksBtn;
}
