package stocks.view.portfolio;

import org.jfree.data.category.DefaultCategoryDataset;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import stocks.controller.GUIController;
import stocks.view.GUIView;

/**
 * This class creates and plots a graph for portfolio performance using given data set.
 *
 * @author Dharmish
 */
public class PortfolioGraph extends javax.swing.JPanel implements GUIView {

  GUIController controller;


  private javax.swing.JComboBox<String> pGPortfolioId;
  private javax.swing.JButton pGViewGraphBtn;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField pGEndDateTxt;
  private javax.swing.JLabel pGErrorLbl;
  private javax.swing.JTextField pGFrequencyTxt;
  private javax.swing.JTextField pGStartDateTxt;


  /**
   * Creates new form PortfolioGraph.
   */
  public PortfolioGraph(GUIController controller) {
    initComponents();
    this.controller = controller;
    controller.setPortfolioGraphView(this);

    pGViewGraphBtn.setActionCommand("PGViewGraph");

    pGPortfolioId.removeAllItems();
    pGPortfolioId.addItem("Select");
    String portfolios = controller.getExistingPortfolios();
    if (!portfolios.isEmpty()) {
      String[] portfolioList = portfolios.substring(1).split("\n");
      for (String port : portfolioList) {
        pGPortfolioId.addItem(port);
      }
    }

    List<Integer> scores = new ArrayList<Integer>();
    Random random = new Random();
    int maxDataPoints = 16;
    int maxScore = 20;
    for (int i = 0; i < maxDataPoints; i++) {
      scores.add(random.nextInt(maxScore));
    }
    this.pGEndDateTxt = pGEndDateTxt;
    this.pGErrorLbl = pGErrorLbl;
    this.pGFrequencyTxt = pGFrequencyTxt;
    this.pGStartDateTxt = pGStartDateTxt;


  }

  /**
   * The following method performs draw graph button.
   *
   * @param listener the listener object.
   */
  @Override
  public void addActionListener(ActionListener listener) {
    pGViewGraphBtn.addActionListener(listener);
  }


  /**
   * The following method represents the plot graph method.
   *
   * @param plotName the name of the plot.
   * @param xAxis    the name of the XAxis.
   * @param yAxis    the name of the YAxis.
   * @param dataset  the dataset of the graph.
   */
  @Override
  public void plotGraph(String plotName, String xAxis, String yAxis,
                        DefaultCategoryDataset dataset) {
    jScrollPane1.setViewportView(new Graph(plotName, xAxis, yAxis, dataset));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {


    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JScrollPane jScrollPane1;

    jLabel1 = new javax.swing.JLabel();
    pGPortfolioId = new javax.swing.JComboBox<>();
    pGViewGraphBtn = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jLabel2 = new javax.swing.JLabel();
    pGStartDateTxt = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    pGEndDateTxt = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    pGFrequencyTxt = new javax.swing.JTextField();
    pGErrorLbl = new javax.swing.JLabel();

    jLabel1.setText("SELECT PORTOFOLIO");

    pGPortfolioId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
            {"Item 1", "Item 2", "Item 3", "Item 4"}));

    pGViewGraphBtn.setText("View Graph");

    jLabel2.setText("START DATE (MM/DD/YYYY)");

    jLabel3.setText("END DATE (MM/DD/YYYY)");

    jLabel4.setText("FREQUENCY");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup().addGroup(layout
                                            .createParallelGroup(javax.swing.
                                                            GroupLayout.Alignment.LEADING,
                                                    false)
                                                    .addComponent(jLabel1,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE)
                                                    .addComponent(pGPortfolioId,
                                                            0, javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(pGViewGraphBtn,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.
                                                    GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout
                                                                    .createParallelGroup(javax
                                                                                    .swing
                                                                                    .GroupLayout
                                                                                    .Alignment
                                                                                    .LEADING,
                                                                            false)
                                                                    .addComponent(jLabel2,
                                                                            javax.swing.GroupLayout
                                                                                    .DEFAULT_SIZE,
                                                                            javax.swing.GroupLayout
                                                                                    .DEFAULT_SIZE,
                                                                            Short.MAX_VALUE)
                                                                    .addComponent(pGStartDateTxt))
                                                            .addGap(18, 18, 18)
                                                            .addGroup(layout
                                                                    .createParallelGroup
                                                                    (javax.swing.GroupLayout
                                                                                    .Alignment
                                                                                    .LEADING,
                                                                            false)
                                                                    .addGroup(layout
                                                                            .createSequentialGroup()
                                                                            .addComponent(jLabel3)
                                                                            .addGap(18,
                                                                                    18,
                                                                                    18)
                                                                            .addComponent(jLabel4))
                                                                    .addGroup(layout
                                                                            .createSequentialGroup()
                                                                            .addComponent(pGEndDateTxt,
                                                                                    javax.swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE,
                                                                                    122,
                                                                                    javax.swing.
                                                                                            GroupLayout
                                                                                            .PREFERRED_SIZE)
                                                                            .addGap(18,
                                                                                    18,
                                                                                    18)
                                                                            .addComponent
                                                                                    (pGFrequencyTxt)
                                                                    )))
                                                    .addComponent(pGErrorLbl))
                                            .addGap(0, 147, Short.MAX_VALUE)))
                            .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.BASELINE)
                                    .addComponent(pGPortfolioId,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pGStartDateTxt,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pGEndDateTxt,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pGFrequencyTxt,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.BASELINE)
                                    .addComponent(pGViewGraphBtn)
                                    .addComponent(pGErrorLbl))
                            .addPreferredGap(javax.swing.LayoutStyle
                                    .ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                    193, Short.MAX_VALUE)
                            .addContainerGap())
    );
  }
}
