package stocks.view.portfolio;

import org.jfree.data.category.DefaultCategoryDataset;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

import stocks.controller.GUIController;
import stocks.view.GUIView;

/**
 * @author Dharmish
 */
public class PortfolioGraph extends javax.swing.JPanel implements GUIView {

  GUIController controller;
  private javax.swing.JTextField PGEndDateTxt;
  private javax.swing.JLabel PGErrorLbl;
  private javax.swing.JTextField PGFrequencyTxt;
  private javax.swing.JComboBox<String> PGPortfolioId;
  private javax.swing.JTextField PGStartDateTxt;
  private javax.swing.JButton PGViewGraphBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  /**
   * Creates new form PortfolioGraph
   */
  public PortfolioGraph(GUIController controller) {
    initComponents();
    this.controller = controller;
    controller.setPortfolioGraphView(this);

    PGViewGraphBtn.setActionCommand("PGViewGraph");

    PGPortfolioId.removeAllItems();
    PGPortfolioId.addItem("Select");
    String portfolios = controller.getExistingPortfolios();
    if (!portfolios.isEmpty()) {
      String[] portfolioList = portfolios.substring(1).split("\n");
      for (String port : portfolioList) {
        PGPortfolioId.addItem(port);
      }
    }

    List<Integer> scores = new ArrayList<Integer>();
    Random random = new Random();
    int maxDataPoints = 16;
    int maxScore = 20;
    for (int i = 0; i < maxDataPoints; i++) {
      scores.add(random.nextInt(maxScore));
    }


  }

  /**
   * The following method performs draw graph button.
   *
   * @param listener the listener object.
   */
  @Override
  public void addActionListener(ActionListener listener) {
    PGViewGraphBtn.addActionListener(listener);
  }

  /**
   * The following method performs summary of the data.
   *
   * @param data the stock data.
   */
  @Override
  public void setSummaryData(Map<String, Map<String, Double>> data) {

  }

  /**
   * The following method represents the plot graph method.
   *
   * @param plotName the name of the plot.
   * @param XAxis    the name of the XAxis.
   * @param YAxis    the name of the YAxis.
   * @param dataset  the dataset of the graph.
   */
  @Override
  public void plotGraph(String plotName, String XAxis, String YAxis,
                        DefaultCategoryDataset dataset) {
    jScrollPane1.setViewportView(new Graph(plotName, XAxis, YAxis, dataset));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    PGPortfolioId = new javax.swing.JComboBox<>();
    PGViewGraphBtn = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jLabel2 = new javax.swing.JLabel();
    PGStartDateTxt = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    PGEndDateTxt = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    PGFrequencyTxt = new javax.swing.JTextField();
    PGErrorLbl = new javax.swing.JLabel();

    jLabel1.setText("SELECT PORTOFOLIO");

    PGPortfolioId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1",
            "Item 2", "Item 3", "Item 4"}));

    PGViewGraphBtn.setText("View Graph");

    jLabel2.setText("START DATE (MM/DD/YYYY)");

    jLabel3.setText("END DATE (MM/DD/YYYY)");

    jLabel4.setText("FREQUENCY");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup().addGroup
                                            (layout.createParallelGroup(javax.swing.
                                                            GroupLayout.Alignment.LEADING,
                                                    false)
                                                    .addComponent(jLabel1,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE)
                                                    .addComponent(PGPortfolioId,
                                                            0, javax.swing.GroupLayout
                                                                    .DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(PGViewGraphBtn,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.
                                                    GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup
                                                                    (javax.swing.GroupLayout
                                                                                    .Alignment
                                                                                    .LEADING,
                                                                            false)
                                                                    .addComponent(jLabel2,
                                                                            javax.swing.GroupLayout
                                                                                    .DEFAULT_SIZE,
                                                                            javax.swing.GroupLayout
                                                                                    .DEFAULT_SIZE,
                                                                            Short.MAX_VALUE)
                                                                    .addComponent(PGStartDateTxt))
                                                            .addGap(18, 18, 18)
                                                            .addGroup(layout.createParallelGroup
                                                                    (javax.swing.GroupLayout
                                                                                    .Alignment
                                                                                    .LEADING,
                                                                            false)
                                                                    .addGroup(layout
                                                                            .createSequentialGroup()
                                                                            .addComponent(jLabel3)
                                                                            .addGap(18,
                                                                                    18,
                                                                                    18)
                                                                            .addComponent(jLabel4))
                                                                    .addGroup(layout
                                                                            .createSequentialGroup()
                                                                            .addComponent(PGEndDateTxt,
                                                                                    javax.swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE,
                                                                                    122,
                                                                                    javax.swing.
                                                                                            GroupLayout
                                                                                            .PREFERRED_SIZE)
                                                                            .addGap(18,
                                                                                    18,
                                                                                    18)
                                                                            .addComponent
                                                                                    (PGFrequencyTxt)
                                                                    )))
                                                    .addComponent(PGErrorLbl))
                                            .addGap(0, 147, Short.MAX_VALUE)))
                            .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.BASELINE)
                                    .addComponent(PGPortfolioId,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PGStartDateTxt,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PGEndDateTxt,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PGFrequencyTxt,
                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.BASELINE)
                                    .addComponent(PGViewGraphBtn)
                                    .addComponent(PGErrorLbl))
                            .addPreferredGap(javax.swing.LayoutStyle
                                    .ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                    193, Short.MAX_VALUE)
                            .addContainerGap())
    );
  }
}
