/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stocks.view.portfolio;

import java.awt.event.ActionListener;
import java.lang.reflect.Field;
import java.util.Map;
import java.util.NoSuchElementException;
import javax.swing.JTextField;
import stocks.controller.GUIController;
import stocks.view.GUIView;

/**
 *
 * @author Dharmish
 */
public class PortfolioCreate extends javax.swing.JPanel implements GUIView{
    GUIController controller;


    @Override
    public String getTextFieldData(String fieldName) {
         try{
            Object o = this; // The object you want to inspect
            Class<?> c = o.getClass();
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            JTextField portfolioName = (JTextField) f.get(o);
            return portfolioName.getText();
        }catch(NoSuchFieldException | IllegalAccessException i){
            throw new IllegalArgumentException("No such field found.\n");
        }
         
        return null;
    }

    @Override
    public void clearTextFieldData(String fieldName) {
        try{
            Object o = this; // The object you want to inspect
            Class<?> c = o.getClass();
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            JTextField portfolioName = (JTextField) f.get(o);
            portfolioName.setText("");
        }catch(NoSuchFieldException | IllegalAccessException i){
            throw new IllegalArgumentException("No such field found.\n");
        }
    }

    @Override
    public void setErrorMessage(String fieldName, String message) {

    }

    /**
     * Creates new form PortfolioCreate
     */
    public PortfolioCreate(GUIController controller) {
        initComponents();
        controller.setCreateView(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        portfolioNameTxt = new javax.swing.JTextField();
        savePortfolioBtn = new javax.swing.JButton();

        jLabel1.setText("Enter portfolio name");

        portfolioNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portfolioNameTxtActionPerformed(evt);
            }
        });

        savePortfolioBtn.setText("Save");
        savePortfolioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePortfolioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(portfolioNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePortfolioBtn))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(portfolioNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savePortfolioBtn)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addActionListener(ActionListener listener){
        savePortfolioBtn.addActionListener(listener);    
    }
    
     
    private void savePortfolioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePortfolioBtnActionPerformed
       
    }//GEN-LAST:event_savePortfolioBtnActionPerformed

    private void portfolioNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portfolioNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portfolioNameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField portfolioNameTxt;
    private javax.swing.JButton savePortfolioBtn;
    // End of variables declaration//GEN-END:variables
}
