package stocks.view.portfolio;

import java.awt.event.ActionListener;

import stocks.controller.GUIController;
import stocks.view.GUIView;

/**
 * The following class represents the Save portfolio panel.
 */
public class PortfolioSave extends javax.swing.JPanel implements GUIView {

  GUIController controller;
  private javax.swing.JComboBox<String> pSPortfolioId;
  private javax.swing.JButton pSSaveAllBtn;
  private javax.swing.JButton pSSaveBtn;
  private javax.swing.JLabel pSErrorLbl;
  private javax.swing.JLabel jLabel1;

  /**
   * Creates new form PortfolioSave.
   *
   * @param controller the GUIController object.
   */
  public PortfolioSave(GUIController controller) {
    initComponents();
    this.controller = controller;
    controller.setPortfolioSaveView(this);
    pSSaveBtn.setActionCommand("PSSave");
    pSSaveAllBtn.setActionCommand("PSSaveAll");

    pSPortfolioId.removeAllItems();
    pSPortfolioId.addItem("Select");
    String portfolios = controller.getExistingPortfolios();
    if (!portfolios.isEmpty()) {
      String[] portfolioList = portfolios.substring(1).split("\n");
      for (String port : portfolioList) {
        pSPortfolioId.addItem(port);
      }
    }

     this.pSPortfolioId = pSPortfolioId;
     this.pSSaveAllBtn = pSSaveAllBtn;
     this.pSSaveBtn = pSSaveBtn;
    this.pSErrorLbl = pSErrorLbl;
    this.jLabel1 = jLabel1;

  }

  /**
   * The following method represents the action listener method.
   *
   * @param listener the listener of the object
   */
  @Override
  public void addActionListener(ActionListener listener) {
    pSSaveBtn.addActionListener(listener);
    pSSaveAllBtn.addActionListener(listener);
  }



  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {



    pSSaveAllBtn = new javax.swing.JButton();
    pSSaveBtn = new javax.swing.JButton();
    pSPortfolioId = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    pSErrorLbl = new javax.swing.JLabel();

    pSSaveAllBtn.setText("Save All");

    pSSaveBtn.setText("Save");

    pSPortfolioId.setModel(new javax.swing.DefaultComboBoxModel<>
            (new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

    jLabel1.setText("SELECT PORTFOLIO");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup
                                    (javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(pSSaveBtn,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle
                                                    .ComponentPlacement.UNRELATED)
                                            .addComponent(pSSaveAllBtn))
                                    .addComponent(pSErrorLbl)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                            .Alignment.TRAILING, false)
                                            .addComponent(pSPortfolioId, javax.swing.GroupLayout
                                                            .Alignment.LEADING, 0,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment
                                                            .LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)))
                            .addContainerGap(252, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pSPortfolioId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.BASELINE)
                                    .addComponent(pSSaveBtn)
                                    .addComponent(pSSaveAllBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pSErrorLbl)
                            .addContainerGap(188, Short.MAX_VALUE))
    );
  }
  // End of variables declaration//GEN-END:variables
}
