
package stocks.view.portfolio;

import java.awt.event.ActionListener;
import java.util.Map;

import stocks.controller.GUIController;
import stocks.view.GUIView;

/**
 * The following class represents the Save portfolio panel.
 */
public class PortfolioSave extends javax.swing.JPanel implements GUIView {

  GUIController controller;

  /**
   * Creates new form PortfolioSave
   * @param controller the GUIController object.
   */
  public PortfolioSave(GUIController controller) {
    initComponents();
    this.controller = controller;
    controller.setPortfolioSaveView(this);
    PSSaveBtn.setActionCommand("PSSave");
    PSSaveAllBtn.setActionCommand("PSSaveAll");

    PSPortfolioId.removeAllItems();
    PSPortfolioId.addItem("Select");
    String portfolios = controller.getExistingPortfolios();
    if (!portfolios.isEmpty()) {
      String[] portfolioList = portfolios.substring(1).split("\n");
      for (String port : portfolioList) {
        PSPortfolioId.addItem(port);
      }
    }

  }

  /**
   * The following method represents the action listener method.
   * @param listener the listener of the object
   */
  @Override
  public void addActionListener(ActionListener listener) {
    PSSaveBtn.addActionListener(listener);
    PSSaveAllBtn.addActionListener(listener);
  }

  /**
   * The following method displays the summary of the stock.
   * @param data the data of the stock.
   */
  @Override
  public void setSummaryData(Map<String, Map<String, Double>> data) {

  }


  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    PSSaveAllBtn = new javax.swing.JButton();
    PSSaveBtn = new javax.swing.JButton();
    PSPortfolioId = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    PSErrorLbl = new javax.swing.JLabel();

    PSSaveAllBtn.setText("Save All");

    PSSaveBtn.setText("Save");

    PSPortfolioId.setModel(new javax.swing.DefaultComboBoxModel<>
            (new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

    jLabel1.setText("SELECT PORTFOLIO");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup
                                    (javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(PSSaveBtn,
                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                    57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle
                                                    .ComponentPlacement.UNRELATED)
                                            .addComponent(PSSaveAllBtn))
                                    .addComponent(PSErrorLbl)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                            .Alignment.TRAILING, false)
                                            .addComponent(PSPortfolioId, javax.swing.GroupLayout
                                                    .Alignment.LEADING, 0,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment
                                                    .LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    Short.MAX_VALUE)))
                            .addContainerGap(252, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PSPortfolioId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.BASELINE)
                                    .addComponent(PSSaveBtn)
                                    .addComponent(PSSaveAllBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(PSErrorLbl)
                            .addContainerGap(188, Short.MAX_VALUE))
    );
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel PSErrorLbl;
  private javax.swing.JComboBox<String> PSPortfolioId;
  private javax.swing.JButton PSSaveAllBtn;
  private javax.swing.JButton PSSaveBtn;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
