package stocks.view.portfolio;

import stocks.controller.GUIController;

/**
 * The following class represents the portfolio main panel.
 */
public class PortfolioMain extends javax.swing.JSplitPane {

  GUIController controller;


  private javax.swing.JSplitPane jSplitPane1;


  /**
   * Creates new form PortfolioMain.
   *
   * @param controller the GUIController object.
   */
  public PortfolioMain(GUIController controller) {
    initComponents();
    this.controller = controller;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    javax.swing.JButton pMGraphBtn;
    javax.swing.JButton pMLoad;
    javax.swing.JButton pMSave;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel3;
    javax.swing.JButton portfolioCreateBtn;
    javax.swing.JButton portfolioViewBtn;

    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel1 = new javax.swing.JPanel();
    portfolioCreateBtn = new javax.swing.JButton();
    portfolioViewBtn = new javax.swing.JButton();
    pMSave = new javax.swing.JButton();
    pMLoad = new javax.swing.JButton();
    pMGraphBtn = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();

    portfolioCreateBtn.setText("Create");
    portfolioCreateBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        portfolioCreateBtnActionPerformed(evt);
      }
    });

    portfolioViewBtn.setText("View");
    portfolioViewBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        portfolioViewBtnActionPerformed(evt);
      }
    });

    pMSave.setText("Save");
    pMSave.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        PMSaveActionPerformed(evt);
      }
    });

    pMLoad.setText("Load");
    pMLoad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        PMLoadActionPerformed(evt);
      }
    });

    pMGraphBtn.setText("Graph");
    pMGraphBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        PMGraphBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax
                                                            .swing.GroupLayout.Alignment.LEADING,
                                                            false)
                                                    .addComponent(portfolioCreateBtn,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE)
                                                    .addComponent(portfolioViewBtn,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            Short.MAX_VALUE)))
                                    .addComponent(pMSave, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pMGraphBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pMLoad, javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(portfolioCreateBtn)
                            .addGap(18, 18, 18)
                            .addComponent(portfolioViewBtn)
                            .addGap(18, 18, 18)
                            .addComponent(pMSave)
                            .addGap(18, 18, 18)
                            .addComponent(pMLoad)
                            .addGap(18, 18, 18)
                            .addComponent(pMGraphBtn)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jSplitPane1.setLeftComponent(jPanel1);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 322, Short.MAX_VALUE)
    );

    jSplitPane1.setRightComponent(jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486,
                            Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324,
                            Short.MAX_VALUE)
    );
  }

  /**
   * The following method represents the action performed by create portfolio.
   *
   * @param evt the Action event object.
   */
  private void portfolioCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {
    jSplitPane1.setRightComponent(new PortfolioCreate(controller));
  }

  /**
   * The following method represents the action performed by create portfolio.
   *
   * @param evt the Action event object.
   */
  private void portfolioViewBtnActionPerformed(java.awt.event.ActionEvent evt) {
    jSplitPane1.setRightComponent(new PortfolioView(controller));
  }

  /**
   * The following method represents the action performed by create portfolio.
   *
   * @param evt the Action event object.
   */
  private void PMLoadActionPerformed(java.awt.event.ActionEvent evt) {
    jSplitPane1.setRightComponent(new PortfolioLoad(controller));
  }

  /**
   * The following method represents the action performed by create portfolio.
   *
   * @param evt the Action event object.
   */

  private void PMSaveActionPerformed(java.awt.event.ActionEvent evt) {
    jSplitPane1.setRightComponent(new PortfolioSave(controller));
  }

  /**
   * The following method represents the action performed by create portfolio.
   *
   * @param evt the Action event object.
   */

  private void PMGraphBtnActionPerformed(java.awt.event.ActionEvent evt) {
    jSplitPane1.setRightComponent(new PortfolioGraph(controller));
  }
}
