/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stocks.view.investment;

import java.awt.event.ActionListener;
import java.lang.reflect.Field;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import stocks.controller.GUIController;
import stocks.model.stock.Stock;
import stocks.view.GUIView;

/**
 *
 * @author Animesh Mane
 */
public class OneTime extends javax.swing.JPanel implements GUIView {
    
    GUIController controller;
    /**
     * Creates new form OneTime
     */
    public OneTime(GUIController controller) {
        initComponents();
        this.controller = controller;
        this.controller.setOneTimeInvestmentView(this);
        saveOneTime.setActionCommand("createOneTime");
        oneInvestmentOption.setActionCommand("oneTime");
        oneInvestmentOption.removeAllItems();
        oneInvestmentOption.addItem("EQUAL");
        oneInvestmentOption.addItem("CUSTOM");
        oneTimePortfolioId.removeAllItems();
        oneTimePortfolioId.addItem("Select");
        oneStocksInPortfolio.removeAllItems();
        oneStocksInPortfolio.addItem("STOCKS");
        String portfolios = controller.getExistingPortfolios();
        if(!portfolios.isEmpty()){
            String[] portfolioList = portfolios.substring(1).split("\n");
            for(String port:portfolioList){
                oneTimePortfolioId.addItem(port);
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        oneTimePortfolioId = new javax.swing.JComboBox();
        oneInvestmentOption = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveOneTime = new javax.swing.JButton();
        oneInvestmentDate = new javax.swing.JTextField();
        oneAmountInvested = new javax.swing.JTextField();
        oneCommissionRate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        oneStocksInPortfolio = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        weightAge = new javax.swing.JTextField();

        jLabel1.setText("ONE TIME STRATEGY");

        jLabel2.setText("ENTER THE INVESTMENT DATE (MM/DD/YYYY)");

        jLabel4.setText("SELECT THE INVESTMENT OPTION");

        jLabel3.setText("SELECT THE PORTFOLIO ");

        oneTimePortfolioId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        oneInvestmentOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("ENTER THE AMOUNT INVESTED");

        jLabel6.setText("ENTER THE COMMISSION RATE");

        saveOneTime.setText("SAVE");

        jLabel7.setText("PLEASE ENTER WEIGHT FOR EACH STOCK (ONLY APPLICABLE FOR CUSTOM WEIGHT)");

        oneStocksInPortfolio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("STOCKS");

        jLabel9.setText("WEIGHTAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oneInvestmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveOneTime, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneInvestmentOption, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(oneTimePortfolioId, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(oneAmountInvested, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneCommissionRate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(oneStocksInPortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(weightAge, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneTimePortfolioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneInvestmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneAmountInvested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oneCommissionRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(oneInvestmentOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oneStocksInPortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveOneTime)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField oneAmountInvested;
    private javax.swing.JTextField oneCommissionRate;
    private javax.swing.JTextField oneInvestmentDate;
    private javax.swing.JComboBox oneInvestmentOption;
    private javax.swing.JComboBox oneStocksInPortfolio;
    private javax.swing.JComboBox oneTimePortfolioId;
    private javax.swing.JButton saveOneTime;
    private javax.swing.JTextField weightAge;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addActionListener(ActionListener listener) {
        saveOneTime.addActionListener(listener);
    }

    @Override
    public void setSummaryData(Map<String, Map<String, Double>> data) {
    }

    @Override
    public String getTextFieldData(String fieldName) {
        try{
            Object o = this; // The object you want to inspect
            Class<?> c = o.getClass();
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            JTextField portfolioName = (JTextField) f.get(o);
            return portfolioName.getText();
        }catch(NoSuchFieldException | IllegalAccessException i){
            throw new IllegalArgumentException("No such field found.\n");
        }
    }

    @Override
    public String getComboFieldData(String fieldName) {
         try{
            Object o = this; // The object you want to inspect
            Class<?> c = o.getClass();
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            JComboBox<String> portfolioName = (JComboBox<String>) f.get(o);
            return (String)portfolioName.getSelectedItem();
        }catch(NoSuchFieldException | IllegalAccessException i){
            throw new IllegalArgumentException("No such field found.\n");
        }
    }

    @Override
    public void clearTextFieldData(String fieldName) {
        try{
            Object o = this; // The object you want to inspect
            Class<?> c = o.getClass();
            Field f = c.getDeclaredField(fieldName);
            f.setAccessible(true);
            JTextField portfolioName = (JTextField) f.get(o);
            portfolioName.setText("");
        }catch(NoSuchFieldException | IllegalAccessException i){
            throw new IllegalArgumentException("No such field found.\n");
        }
    }

    @Override
    public void setErrorMessage(String fieldName, String message) {
    }
    
    public void updateStockComboBox (List<Stock> stocksInPortfolio) {
     oneStocksInPortfolio.removeAllItems();
     for(Stock stock:stocksInPortfolio) {
         String stocksTickerSymbol = stock.getTickerSymbol();
         oneStocksInPortfolio.addItem(stocksTickerSymbol);
     }
    }
   
}
